class Genre

ARRAY =	[{:artist=>"A$AP Rocky", :title=>"Peso", :genre=>"dance", :format=>"mp3"}, 
		{:artist=>"Action Bronson", :title=>"Larry Csonka", :genre=>"indie", :format=>"mp3"}, 
		{:artist=>"Adele", :title=>"Rolling In the Deep", :genre=>"folk", :format=>"mp3"}, 
		{:artist=>"Adele", :title=>"Someone Like You", :genre=>"country", :format=>"mp3"}, 
		{:artist=>"AraabMuzik", :title=>"Streetz Tonight", :genre=>"folk", :format=>"mp3"}, 
		{:artist=>"Atlas Sound", :title=>"Mona Lisa", :genre=>"pop", :format=>"mp3"}, 
		{:artist=>"Azealia Banks", :title=>"212", :genre=>"hip-hop", :format=>"mp3"}, 
		{:artist=>"Battles", :title=>"Ice Cream (Feat. Matias Aguayo)", :genre=>"rock", :format=>"mp3"}, 
		{:artist=>"Beyonce", :title=>"1+1", :genre=>"house", :format=>"mp3"}, 
		{:artist=>"Beyonce", :title=>"Countdown", :genre=>"pop", :format=>"mp3"}, 
		{:artist=>"Bill Callahan", :title=>"Riding for the Feeling", :genre=>"indie", :format=>"mp3"}, 
		{:artist=>"Blawan", :title=>"Getting Me Down", :genre=>"hip-hop", :format=>"mp3"}, 
		{:artist=>"Bon Iver", :title=>"Holocene", :genre=>"house", :format=>"mp3"}, 
		{:artist=>"Bon Iver", :title=>"Perth", :genre=>"pop", :format=>"mp3"}, 
		{:artist=>"Britney Spears", :title=>"Till the World Ends (The Femme Fatale Remix) (feat.Kesha & Nicki Minaj)", :genre=>"pop", :format=>"mp3"}, 
		{:artist=>"Burial", :title=>"Street Halo", :genre=>"rock", :format=>"mp3"}, 
		{:artist=>"Cass McCombs", :title=>"County Line", :genre=>"country", :format=>"mp3"}, 
		{:artist=>"Charli XCX", :title=>"Stay Away", :genre=>"rock", :format=>"mp3"}, 
		{:artist=>"Cities Aviv", :title=>"Coastin'", :genre=>"dance", :format=>"mp3"}, 
		{:artist=>"Clams Casino", :title=>"Motivation", :genre=>"hip-hop", :format=>"mp3"}, 
		{:artist=>"Cold Cave", :title=>"The Great Pan is Dead", :genre=>"house", :format=>"mp3"}, 
		{:artist=>"Cults", :title=>"Abducted", :genre=>"rock", :format=>"mp3"}, 
		{:artist=>"Cut Copy", :title=>"Need You Now", :genre=>"rap", :format=>"mp3"}, 
		{:artist=>"Danny Brown", :title=>"Monopoly", :genre=>"electro", :format=>"mp3"}, 
		{:artist=>"Destroyer", :title=>"Chinatown", :genre=>"country", :format=>"mp3"}, 
		{:artist=>"DJ Khaled", :title=>"I'm On One (ft. Drake, Rick Ross & Lil Wayne)", :genre=>"pop", :format=>"mp3"}, 
		{:artist=>"DJ Quik", :title=>"Killer Dope", :genre=>"country", :format=>"mp3"}, 
		{:artist=>"Drake", :title=>"Buried Alive (Interlude) (Feat. Kendrick Lamar)", :genre=>"dance", :format=>"mp3"}, 
		{:artist=>"Drake", :title=>"Headlines", :genre=>"folk", :format=>"mp3"}, 
		{:artist=>"Dum Dum Girls", :title=>"Wrong Feels Right", :genre=>"folk", :format=>"mp3"}, 
		{:artist=>"Eleanor Friedberger", :title=>"My Mistakes", :genre=>"country", :format=>"mp3"}, 
		{:artist=>"EMA", :title=>"California", :genre=>"hip-hop", :format=>"mp3"}, 
		{:artist=>"Fever Ray", :title=>"The Wolf", :genre=>"electro", :format=>"mp3"}, 
		{:artist=>"Fleet Foxes", :title=>"Grown Ocean", :genre=>"folk", :format=>"mp3"}, 
		{:artist=>"Frank Ocean", :title=>"Novacane", :genre=>"dance", :format=>"mp3"}, 
		{:artist=>"Fucked Up", :title=>"Queen of Hearts", :genre=>"folk", :format=>"mp3"}, 
		{:artist=>"Gang Gang Dance", :title=>"Glass Jar", :genre=>"electro", :format=>"mp3"}, 
		{:artist=>"Girls", :title=>"Vomit", :genre=>"house", :format=>"mp3"}, 
		{:artist=>"Grimes", :title=>"Vanessa", :genre=>"rock", :format=>"mp3"}, 
		{:artist=>"Holy Ghost", :title=>"Jam For Jerry", :genre=>"house", :format=>"mp3"}, 
		{:artist=>"Iceage", :title=>"You're Blessed", :genre=>"rap", :format=>"mp3"}, 
		{:artist=>"Ill Blu", :title=>"Meltdown", :genre=>"house", :format=>"mp3"}, 
		{:artist=>"Jacques Greene", :title=>"Another Girl", :genre=>"rock", :format=>"mp3"}, 
		{:artist=>"Jai Paul", :title=>"BTSTU", :genre=>"electro", :format=>"mp3"}, 
		{:artist=>"James Blake", :title=>"The Wilhelm Scream", :genre=>"electro", :format=>"mp3"}, 
		{:artist=>"Jamie xx & Gill Scott-Heron", :title=>"I'll Take Care Of You", :genre=>"pop", :format=>"mp3"}, 
		{:artist=>"Jamie xx", :title=>"Far Nearer", :genre=>"rock", :format=>"mp3"}, 
		{:artist=>"Jay-Z & Kanye West", :title=>"Niggas In Paris", :genre=>"dance", :format=>"mp3"}, 
		{:artist=>"Jay-Z & Kanye West", :title=>"Otis (ft. Otis Redding)", :genre=>"folk", :format=>"mp3"}, 
		{:artist=>"John Maus", :title=>"Believer", :genre=>"indie", :format=>"mp3"}, 
		{:artist=>"Julianna Barwick", :title=>"Prizewinning", :genre=>"pop", :format=>"mp3"}, 
		{:artist=>"Junior Boys", :title=>"Banana Ripple", :genre=>"indie", :format=>"mp3"}, 
		{:artist=>"Katy B", :title=>"Broken Record", :genre=>"pop", :format=>"mp3"}, 
		{:artist=>"Kelly Rowland", :title=>"Motivation (ft. Lil Wayne)", :genre=>"house", :format=>"mp3"}, 
		{:artist=>"Kendrick Lamar", :title=>"A.D.H.D", :genre=>"rap", :format=>"mp3"}, 
		{:artist=>"Kreayshawn", :title=>"Gucci Gucci", :genre=>"house", :format=>"mp3"}, 
		{:artist=>"Kurt Vile", :title=>"Jesus Fever", :genre=>"rock", :format=>"mp3"}, 
		{:artist=>"Lana Del Rey", :title=>"Video Games", :genre=>"hip-hop", :format=>"mp3"}, 
		{:artist=>"Liturgy", :title=>"Generation", :genre=>"rap", :format=>"mp3"}, 
		{:artist=>"M83", :title=>"Intro (ft. Zola Jesus)", :genre=>"indie", :format=>"mp3"}, 
		{:artist=>"M83", :title=>"Midnight City", :genre=>"house", :format=>"mp3"}, 
		{:artist=>"Mr. Muthafuckin eXquire", :title=>"Huzzah (Remix ft. Despot, Das Racist, Danny Brown and El-P)", :genre=>"rock", :format=>"mp3"}, 
		{:artist=>"Neon Indian", :title=>"Polish Girl", :genre=>"rock", :format=>"mp3"}, 
		{:artist=>"Nicholas Jaar", :title=>"Space Is Only Noise If You Can See", :genre=>"house", :format=>"mp3"}, 
		{:artist=>"Nicki Minaj", :title=>"Super Bass", :genre=>"rap", :format=>"mp3"}, 
		{:artist=>"Oneohtrix Point Never", :title=>"Replica", :genre=>"country", :format=>"mp3"}, 
		{:artist=>"Panda Bear", :title=>"Last Night At The Jetty", :genre=>"indie", :format=>"mp3"}, 
		{:artist=>"Peaking Lights", :title=>"All the Sun That Shines", :genre=>"indie", :format=>"mp3"}, 
		{:artist=>"PJ Harvey", :title=>"The Words That Maketh Murder", :genre=>"folk", :format=>"mp3"}, 
		{:artist=>"Purity Ring", :title=>"Ungirthed", :genre=>"rap", :format=>"mp3"}, 
		{:artist=>"Real Estate", :title=>"Green Aisles", :genre=>"country", :format=>"mp3"}, 
		{:artist=>"Real Estate", :title=>"It's Real", :genre=>"hip-hop", :format=>"mp3"}, 
		{:artist=>"Rihanna", :title=>"We Found Love (ft. Calvin Harris)", :genre=>"indie", :format=>"mp3"}, 
		{:artist=>"Sandro Perri", :title=>"Changes", :genre=>"pop", :format=>"mp3"}, 
		{:artist=>"SBTRKT", :title=>"Wildfire", :genre=>"country", :format=>"mp3"}, 
		{:artist=>"Sepalcure", :title=>"Pencil Pimp", :genre=>"rap", :format=>"mp3"}, 
		{:artist=>"Shabazz Palaces", :title=>"Swerve... The Reeping of All That Is Worthwhile (Noir Not Withstanding)", :genre=>"indie", :format=>"mp3"}, 
		{:artist=>"Soulja Boy", :title=>"Zan With That Lean", :genre=>"hip-hop", :format=>"mp3"}, 
		{:artist=>"St. Vincent", :title=>"Cruel", :genre=>"electro", :format=>"mp3"}, 
		{:artist=>"The Field", :title=>"Then It's White", :genre=>"rock", :format=>"mp3"}, 
		{:artist=>"The Joy Formidable", :title=>"Whirring", :genre=>"rock", :format=>"mp3"}, 
		{:artist=>"The Men", :title=>"Bataille", :genre=>"hip-hop", :format=>"mp3"}, 
		{:artist=>"The Rapture", :title=>"How Deep Is Your Love", :genre=>"folk", :format=>"mp3"}, 
		{:artist=>"The Weeknd", :title=>"House of Balloons", :genre=>"hip-hop", :format=>"mp3"}, 
		{:artist=>"The Weeknd", :title=>"The Morning", :genre=>"dance", :format=>"mp3"}, 
		{:artist=>"Thee Oh Sees", :title=>"The Dream", :genre=>"pop", :format=>"mp3"}, 
		{:artist=>"Thundercat", :title=>"For Love I Come", :genre=>"dance", :format=>"mp3"}, 
		{:artist=>"Tiger & Woods", :title=>"Gin Nation", :genre=>"hip-hop", :format=>"mp3"}, 
		{:artist=>"Todd Terje", :title=>"Snooze 4 Love", :genre=>"hip-hop", :format=>"mp3"}, 
		{:artist=>"Toro Y Moi", :title=>"New Beat", :genre=>"dance", :format=>"mp3"}, 
		{:artist=>"tUnE-yArDs", :title=>"Bizness", :genre=>"dance", :format=>"mp3"}, 
		{:artist=>"tUnE-yArDs", :title=>"Powa", :genre=>"country", :format=>"mp3"}, 
		{:artist=>"Ty Segall", :title=>"Goodbye Bread", :genre=>"dance", :format=>"mp3"}, 
		{:artist=>"Tyler the Creator", :title=>"Yonkers", :genre=>"folk", :format=>"mp3"}, 
		{:artist=>"Unknown Mortal Orchestra", :title=>"Ffunny Ffrends", :genre=>"hip-hop", :format=>"mp3"}, 
		{:artist=>"Washed Out", :title=>"Amor Fati", :genre=>"folk", :format=>"mp3"}, 
		{:artist=>"Wild Flag", :title=>"Romance", :genre=>"hip-hop", :format=>"mp3"}, 
		{:artist=>"Yuck", :title=>"Get Away", :genre=>"indie", :format=>"mp3"}, 
		{:artist=>"Zoo Kid", :title=>"Out Getting Ribs", :genre=>"hip-hop", :format=>"mp3"}]

		
		dance = []
		def over_it
			ARRAY.each do |h|
				array.each do |k,v|
					if v[value[3]] == "dance"
					dance << v[value[3]]
					end
				p dance
			end
		end

	end
end

test = Genre.new 
p test.over_it

